spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Health
    username: root
    password: dibya
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  boot:
    admin:
      client:
        url: http://localhost:1111
        instance:
          service-url: http://localhost:8082
        auto-registration: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true
