spring:
  application:
    name: email-service
  boot:
    admin:
      client:
        url: http://localhost:1111  # URL of your Spring Boot Admin Server
        instance:
          service-host-type: ip

  mail:
    host: smtp.gmail.com
    port: 587
    username: dibyajyoti.panigrahi.dipu@gmail.com
    password: suwb rvry ioov qikn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4444

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
