spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dibyajyoti.panigrahi.dipu@gmail.com
    password: suwb rvry ioov qikn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 4444

